# Generated by Django 5.2.4 on 2025-08-01 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="borrow",
            name="returned",
            field=models.BooleanField(default=False),
        ),
    ]
